### PR TITLE
Added PATCH as a partial update support

### PR DESCRIPTION
**Pull request by klimesf**
Added support for partial update when method `PATCH` is used.

### CODE REVIEW

**Comment by freezy-sk** [comment]
:+1:

**Comment by newPOPE** [comment]
Thanks for PR.

I am thinking about that `PATCH` method will be "linked" to partialUpdate directly. No needed enabling that functionality. It will be bc break but what do you think?

**Comment by klimesf** [comment]
@newPOPE I don't think the BC break is worth it. Everyone who wants to use the `partialUpdate` method  can just set the flag to true in RouterFactory, which is not much of an overhead.

**Comment by newPOPE** [comment]
@klimesf okay

**Comment by klimesf** [comment]
@newPOPE Thanks for fast response! :)

**Pull request merged**
